//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ajinomoto_Weighing_SystemEntities : DbContext
    {
        public Ajinomoto_Weighing_SystemEntities()
            : base("name=Ajinomoto_Weighing_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogBagSeperate> LogBagSeperates { get; set; }
        public virtual DbSet<LogChangeLot> LogChangeLots { get; set; }
        public virtual DbSet<LogChangeLotV2> LogChangeLotV2 { get; set; }
        public virtual DbSet<LogEditInventory> LogEditInventories { get; set; }
        public virtual DbSet<LogEditMatReceive> LogEditMatReceives { get; set; }
        public virtual DbSet<LogEndBatch> LogEndBatches { get; set; }
        public virtual DbSet<LogInventory> LogInventories { get; set; }
        public virtual DbSet<LogMatRecieve> LogMatRecieves { get; set; }
        public virtual DbSet<LogMatRecieve_EditQty> LogMatRecieve_EditQty { get; set; }
        public virtual DbSet<LogPrint_BagSep> LogPrint_BagSep { get; set; }
        public virtual DbSet<LogPrint_MatRe> LogPrint_MatRe { get; set; }
        public virtual DbSet<LogPrint_Prod> LogPrint_Prod { get; set; }
        public virtual DbSet<LogPrint_ProdBag> LogPrint_ProdBag { get; set; }
        public virtual DbSet<LogProdDetail> LogProdDetails { get; set; }
        public virtual DbSet<LogProdDetail_6> LogProdDetail_6 { get; set; }
        public virtual DbSet<LogProdPlan> LogProdPlans { get; set; }
        public virtual DbSet<LogRePrint_MatRe> LogRePrint_MatRe { get; set; }
        public virtual DbSet<LogRePrint_Prod> LogRePrint_Prod { get; set; }
        public virtual DbSet<LogReweigh> LogReweighs { get; set; }
        public virtual DbSet<LogReWeightOrder> LogReWeightOrders { get; set; }
        public virtual DbSet<LogSpecialCal> LogSpecialCals { get; set; }
        public virtual DbSet<LogSpecialOrder> LogSpecialOrders { get; set; }
        public virtual DbSet<LogUpPlan> LogUpPlans { get; set; }
        public virtual DbSet<MasterCauseChangeLot> MasterCauseChangeLots { get; set; }
        public virtual DbSet<MasterCauseEndBatch> MasterCauseEndBatches { get; set; }
        public virtual DbSet<MasterCauseReprint> MasterCauseReprints { get; set; }
        public virtual DbSet<MasterIng> MasterIngs { get; set; }
        public virtual DbSet<MasterPage> MasterPages { get; set; }
        public virtual DbSet<MasterPosition> MasterPositions { get; set; }
        public virtual DbSet<MasterRecipe> MasterRecipes { get; set; }
        public virtual DbSet<MasterRecipe_6> MasterRecipe_6 { get; set; }
        public virtual DbSet<MasterRecipeName> MasterRecipeNames { get; set; }
        public virtual DbSet<MasterRecpCook> MasterRecpCooks { get; set; }
        public virtual DbSet<MasterRecpStation> MasterRecpStations { get; set; }
        public virtual DbSet<MasterShift> MasterShifts { get; set; }
        public virtual DbSet<MasterStation> MasterStations { get; set; }
        public virtual DbSet<MasterSupplier> MasterSuppliers { get; set; }
        public virtual DbSet<MasterUser> MasterUsers { get; set; }
        public virtual DbSet<MonitorStation> MonitorStations { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Position_Page> Position_Page { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Page> User_Page { get; set; }
    }
}
