//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBagSeperate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogBagSeperate()
        {
            this.LogRePrint_MatRe = new HashSet<LogRePrint_MatRe>();
        }
    
        public long BagID { get; set; }
        public string SupCode { get; set; }
        public string IngItemNo { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public string BagNo { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<decimal> BagWeight { get; set; }
        public string ExpDate { get; set; }
        public Nullable<long> LogPrint_MatReID { get; set; }
        public string StickerText { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<bool> IsReprint { get; set; }
        public Nullable<decimal> UsedWeight { get; set; }
        public Nullable<bool> IsEmpty { get; set; }
        public Nullable<bool> IsSkipped { get; set; }
        public string MFGDate { get; set; }
    
        public virtual LogMatRecieve LogMatRecieve { get; set; }
        public virtual LogPrint_MatRe LogPrint_MatRe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogRePrint_MatRe> LogRePrint_MatRe { get; set; }
    }
}
