//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogChangeLotV2
    {
        public long LogID { get; set; }
        public Nullable<long> ProdDeID { get; set; }
        public Nullable<System.DateTime> FromProdDate { get; set; }
        public string FromLotNo { get; set; }
        public Nullable<int> FromBatch { get; set; }
        public Nullable<System.DateTime> ToProdDate { get; set; }
        public string ToLotNo { get; set; }
        public Nullable<int> ToBatch { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string ChangeUser { get; set; }
    }
}
