//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEditMatReceive
    {
        public long LogID { get; set; }
        public string Action { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string SubCode { get; set; }
        public string IngItemNo { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> EditWeight { get; set; }
        public Nullable<int> QtySeperate { get; set; }
        public Nullable<int> EditQtySeperate { get; set; }
    }
}
