//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEditInventory
    {
        public long LogID { get; set; }
        public string EditFrom { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public string IngItemNo { get; set; }
        public Nullable<decimal> OldCarryOver { get; set; }
        public Nullable<decimal> OldRecieve { get; set; }
        public Nullable<decimal> OldSumCarryRec { get; set; }
        public Nullable<decimal> OldUsed { get; set; }
        public Nullable<decimal> OldRemains { get; set; }
        public Nullable<decimal> CarryOver { get; set; }
        public Nullable<decimal> Recieve { get; set; }
        public Nullable<decimal> SumCarryRec { get; set; }
        public Nullable<decimal> Used { get; set; }
        public Nullable<decimal> Remains { get; set; }
    }
}
