//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInventory
    {
        public long Inventory_ID { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public Nullable<int> RecpID { get; set; }
        public string IngItemNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> CarryOver { get; set; }
        public Nullable<decimal> Recieve { get; set; }
        public Nullable<decimal> SumCarryRec { get; set; }
        public Nullable<decimal> Used { get; set; }
        public Nullable<decimal> Remains { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    }
}
