//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMatRecieve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogMatRecieve()
        {
            this.LogBagSeperates = new HashSet<LogBagSeperate>();
        }
    
        public long MatRe_ID { get; set; }
        public string SupCode { get; set; }
        public string IngItemNo { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string UserName { get; set; }
        public string ExpDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> QtySeperate { get; set; }
        public Nullable<bool> IsEditQty { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public string MFGDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBagSeperate> LogBagSeperates { get; set; }
        public virtual LogMatRecieve_EditQty LogMatRecieve_EditQty { get; set; }
        public virtual MasterIng MasterIng { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
