//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMatRecieve_EditQty
    {
        public long EditQty_ID { get; set; }
        public string SupCode { get; set; }
        public string IngItemNo { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public string Username { get; set; }
        public Nullable<int> QtyBefore { get; set; }
        public Nullable<int> QtyEdit { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    
        public virtual LogMatRecieve LogMatRecieve { get; set; }
    }
}
