//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPrint_BagSep
    {
        public long LogPrintdetail_ID { get; set; }
        public string PrinterIP { get; set; }
        public string IngItemNo { get; set; }
        public string IngDesc { get; set; }
        public string IngName { get; set; }
        public string BagNo { get; set; }
        public Nullable<System.DateTime> SepDate { get; set; }
        public string UserSep { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ExpDate { get; set; }
        public string QrCodeText { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
