//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogProdDetail_6
    {
        public long ProdDeID_6 { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> Shift { get; set; }
        public string UserProdSta6 { get; set; }
        public Nullable<int> CookingNo { get; set; }
        public Nullable<decimal> RecipeWeight { get; set; }
        public Nullable<decimal> RealWeight { get; set; }
        public string StirrPotNo { get; set; }
        public string Qrcodetext_Prod { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsRePrint { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
    
        public virtual LogProdDetail LogProdDetail { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
