//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogProdDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogProdDetail()
        {
            this.LogReWeightOrders = new HashSet<LogReWeightOrder>();
        }
    
        public long ProdDeID { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> Shift { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> RecipeWeight { get; set; }
        public Nullable<decimal> RealWeight { get; set; }
        public Nullable<decimal> PotWeight { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string Qrcodetext_Prod { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<bool> IsReweight { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsReprint { get; set; }
    
        public virtual LogPrint_Prod LogPrint_Prod { get; set; }
        public virtual LogProdDetail_6 LogProdDetail_6 { get; set; }
        public virtual LogProdPlan LogProdPlan { get; set; }
        public virtual MasterUser MasterUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogReWeightOrder> LogReWeightOrders { get; set; }
    }
}
