//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPrint_Prod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogPrint_Prod()
        {
            this.LogRePrint_Prod = new HashSet<LogRePrint_Prod>();
        }
    
        public long PrintID_Prod { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public Nullable<bool> Is_6 { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsRePrint { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
    
        public virtual LogProdDetail LogProdDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogRePrint_Prod> LogRePrint_Prod { get; set; }
    }
}
