//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPrint_ProdBag
    {
        public long LogPrintdetail_ID { get; set; }
        public string PrinterIP { get; set; }
        public string ProdDate { get; set; }
        public string RecipeName { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string StationName { get; set; }
        public Nullable<System.DateTime> ProductDatetime { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> PotNo { get; set; }
        public string BagNo { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string QrCodeText { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string UserProd { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> RecpNameID { get; set; }
        public Nullable<int> StationID { get; set; }
        public string PotName { get; set; }
    }
}
