//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRePrint_MatRe
    {
        public long RePrintID_MatRe { get; set; }
        public string SupCode { get; set; }
        public string IngItemNo { get; set; }
        public string PalletNo { get; set; }
        public string LotNo { get; set; }
        public string BagNo { get; set; }
        public int Rev { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string UserName { get; set; }
        public Nullable<long> CReprintID { get; set; }
        public string CReprintText { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual LogBagSeperate LogBagSeperate { get; set; }
    }
}
