//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogReweigh
    {
        public long ReweighID { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public int Rev { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string UserReweigh { get; set; }
        public Nullable<long> BagID_ReWeight { get; set; }
        public Nullable<decimal> PotWeight { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<long> LogPrint_ProdBagID { get; set; }
        public Nullable<bool> IsPrint { get; set; }
    
        public virtual LogReWeightOrder LogReWeightOrder { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
