//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRePrint_Prod
    {
        public long RePrintID_Prod { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public int Revision { get; set; }
        public string UserReprint { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<long> CReprintID { get; set; }
        public string CReprintText { get; set; }
        public Nullable<bool> IsNewProdDate { get; set; }
        public string NewQrCodetext { get; set; }
    
        public virtual LogPrint_Prod LogPrint_Prod { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
