//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogReWeightOrder
    {
        public long LogReWeight_OrderID { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int BatchNo { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public long BagID { get; set; }
        public string ProdUser { get; set; }
        public int Rev { get; set; }
        public Nullable<decimal> RecipeWeight { get; set; }
        public Nullable<decimal> RemainsWeight { get; set; }
        public Nullable<decimal> DiffWeight { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> OrderDatetime { get; set; }
        public string OrderUser { get; set; }
        public Nullable<bool> IsFin { get; set; }
    
        public virtual LogProdDetail LogProdDetail { get; set; }
        public virtual LogReweigh LogReweigh { get; set; }
    }
}
