//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSpecialCal
    {
        public long SpecialCalID { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public int BatchNo { get; set; }
        public long StaID { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Unit { get; set; }
    
        public virtual LogSpecialOrder LogSpecialOrder { get; set; }
    }
}
