//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRecpStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterRecpStation()
        {
            this.MasterRecipes = new HashSet<MasterRecipe>();
        }
    
        public int RecpStaID { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int PotCnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterRecipe> MasterRecipes { get; set; }
        public virtual MasterRecipeName MasterRecipeName { get; set; }
        public virtual MasterStation MasterStation { get; set; }
    }
}
