//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRecipe
    {
        public long RecpID { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public decimal Weight { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TolerancePlus { get; set; }
        public Nullable<decimal> ToleranceMinus { get; set; }
        public Nullable<bool> IsPot { get; set; }
        public Nullable<decimal> StanDTime { get; set; }
    
        public virtual MasterRecipe_6 MasterRecipe_6 { get; set; }
        public virtual MasterRecpStation MasterRecpStation { get; set; }
    }
}
