//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRecipe_6
    {
        public long RecpID_6 { get; set; }
        public int RecpNameID { get; set; }
        public int StaID { get; set; }
        public int PotNo { get; set; }
        public string IngItemNo { get; set; }
        public Nullable<int> CookNo { get; set; }
        public Nullable<int> PotOrder { get; set; }
        public Nullable<int> PotSub { get; set; }
    
        public virtual MasterRecipe MasterRecipe { get; set; }
    }
}
