//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterIng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterIng()
        {
            this.LogMatRecieves = new HashSet<LogMatRecieve>();
        }
    
        public long IngID { get; set; }
        public string SupCode { get; set; }
        public string IngItemNo { get; set; }
        public string IngName { get; set; }
        public string IngDescripton { get; set; }
        public Nullable<decimal> IngPackWeigh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogMatRecieve> LogMatRecieves { get; set; }
        public virtual MasterSupplier MasterSupplier { get; set; }
    }
}
