//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRecpCook
    {
        public int RecpCookID { get; set; }
        public int RecpNameID { get; set; }
        public int CookNo { get; set; }
        public int PotOrder { get; set; }
        public int PotSub { get; set; }
    
        public virtual MasterRecipeName MasterRecipeName { get; set; }
    }
}
