//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterShift
    {
        public int ShiftID { get; set; }
        public int StaID { get; set; }
        public int ShiftNo { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> StopTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual MasterStation MasterStation { get; set; }
    }
}
