//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorStation
    {
        public int StaID { get; set; }
        public string StaName { get; set; }
        public string RecpName { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> PlanBatch { get; set; }
        public Nullable<int> CurrentBatch { get; set; }
        public string UserName { get; set; }
    }
}
