//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoPrintMatRe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.LogChangeLots = new HashSet<LogChangeLot>();
            this.LogEndBatches = new HashSet<LogEndBatch>();
            this.LogProdPlans = new HashSet<LogProdPlan>();
            this.LogSpecialOrders = new HashSet<LogSpecialOrder>();
        }
    
        public long PlanID { get; set; }
        public Nullable<long> UpPlanID { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int RecpNameID { get; set; }
        public Nullable<int> PlanBatch { get; set; }
        public Nullable<bool> IsChangeLot { get; set; }
        public Nullable<bool> IsEndBatch { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogChangeLot> LogChangeLots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEndBatch> LogEndBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogProdPlan> LogProdPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogSpecialOrder> LogSpecialOrders { get; set; }
        public virtual LogUpPlan LogUpPlan { get; set; }
        public virtual MasterRecipeName MasterRecipeName { get; set; }
    }
}
